import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/AppContext";
import { ModalProvider } from "@/context/ModalContext";
import CreateAccountModal from "@/components/modal/CreateAccountModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ModalProvider>
          <UserProvider>
            {children}
          <CreateAccountModal />
          </UserProvider>
        </ModalProvider>
        </body>
    </html>
  );
}
